<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shoofly.Data\Shoofly.Data.csproj" />
    <ProjectReference Include="..\Shoofly.Service\Shoofly.Service.csproj" />
    <ProjectReference Include="..\Shoofly.Shared\Shoofly.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Authorization\Commands\Handlers\" />
    <Folder Include="Features\Authorization\Commands\Models\" />
    <Folder Include="Features\Authorization\Commands\Validations\" />
    <Folder Include="Features\Auth\Queries\" />
    <Folder Include="Features\Client\Queries\Handlers\" />
    <Folder Include="Features\Client\Queries\Models\" />
    <Folder Include="Features\Client\Queries\Results\" />
    <Folder Include="Mapping\Clients\QueryMapping\" />
    <Folder Include="Mapping\Roles\CommandMapping\" />
  </ItemGroup>

</Project>
