<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shoofly.Data\Shoofly.Data.csproj" />
    <ProjectReference Include="..\Shoofly.Infrastructure\Shoofly.Infrastructure.csproj" />
    <ProjectReference Include="..\Shoofly.Shared\Shoofly.Shared.csproj" />
  </ItemGroup>

</Project>
